apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
      - name: notification-service
        image: your-dockerhub-username/notification-service:latest
        ports:
        - containerPort: 8000
        env:
        - name: RABBITMQ_URI
          value: "amqp://novell:novell@123@172.105.51.216:5672/"
---
apiVersion: v1
kind: Service
metadata:
  name: notification-service
spec:
  selector:
    app: notification-service
  ports:
  - protocol: TCP
    port: 8003
    targetPort: 8000
  type: ClusterIP
