apiVersion: apps/v1
kind: Deployment
metadata:
  name: notificationgreen-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notificationgreen-service
  template:
    metadata:
      labels:
        app: notificationgreen-service
    spec:
      containers:
      - name: notificationgreen-service
        image: anurag2911/notificationgreen-service:latest
        ports:
        - containerPort: 8000
        env:
        - name: MONGODB_URI
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: MONGODB_URI
        - name: RABBITMQ_URI
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: RABBITMQ_URI
        - name: JWT_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: JWT_SECRET_KEY  
---
apiVersion: v1
kind: Service
metadata:
  name: notificationgreen-service
spec:
  selector:
    app: notificationgreen-service
  ports:
  - protocol: TCP
    port: 8003
    targetPort: 8000
  type: ClusterIP
