name: Build and Push Microservices

on:
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [auth-service, finance-service, notification-service, analytics-service]  

    services:
      docker:
        image: docker:19.03.12
        options: --privileged
        ports:
          - 2375:2375
        env:
          DOCKER_TLS_CERTDIR: ""

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Copy common folder into each service
      - name: Copy common folder into each service
        run: |
          cp -r ./common ./auth-service/common
          cp -r ./common ./finance-service/common
          cp -r ./common ./notification-service/common
          cp -r ./common ./analytics-service/common  # Added analytics-service

      - name: Build and push ${{ matrix.service }} Docker image
        run: |
          docker build -t anurag2911/${{ matrix.service }}:${{ github.sha }} -t anurag2911/${{ matrix.service }}:latest ./${{ matrix.service }}
          docker push anurag2911/${{ matrix.service }}:${{ github.sha }}
          docker push anurag2911/${{ matrix.service }}:latest
