name: Build and Push Green Microservices

on:
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [auth-service, finance-service, notification-service, analytics-service]  # Keep this naming convention for the services based on folder names

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Copy common folder into each service
      - name: Copy common folder into each service
        run: |
          cp -r ./common ./auth-service/common
          cp -r ./common ./finance-service/common
          cp -r ./common ./notification-service/common
          cp -r ./common ./analytics-service/common

      # Build and push Docker image with green naming convention
      - name: Build and push ${{ matrix.service }} Green Docker image
        run: |
          # Extract the base service name by removing '-service'
          service_name=$(echo "${{ matrix.service }}" | sed 's/-service//')
          
          # Construct the new image name by appending 'green' and adding '-service' again
          green_image_name="${service_name}green-service"
          
          # Build and push Docker image using the new naming convention
          docker build -t anurag2911/$green_image_name:latest -t anurag2911/$green_image_name:${{ github.sha }} ./${{ matrix.service }}
          docker push anurag2911/$green_image_name:latest
          docker push anurag2911/$green_image_name:${{ github.sha }}
