name: Build and Push Microservices

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:19.03.12
        options: --privileged
        ports:
          - 2375:2375
        env:
          DOCKER_TLS_CERTDIR: ""

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Log in to Docker Hub (replace with your Docker Hub username and password stored in secrets)
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build and push auth-service
      - name: Build and push auth-service Docker image
        run: |
          docker build -t your-dockerhub-username/auth-service:latest ./auth-service
          docker push your-dockerhub-username/auth-service:latest

      # Build and push finance-service
      - name: Build and push finance-service Docker image
        run: |
          docker build -t your-dockerhub-username/finance-service:latest ./finance-service
          docker push your-dockerhub-username/finance-service:latest

      # Build and push notification-service
      - name: Build and push notification-service Docker image
        run: |
          docker build -t your-dockerhub-username/notification-service:latest ./notification-service
          docker push your-dockerhub-username/notification-service:latest
